### ISSUE TITLE
change from esx_vehicleshop to d3x_vehicleshop

### ISSUE THREAD

**Issue by xBrunex** [Duart3x/d3x_vehicleshop#3]
Hello

Can you tell us which basic scripts are used in all RP servers that we need to modify?
And what must we change for this to work 100% instead of esx_vehicleshop?

Thanks for your work and very good job on it

**Comment by Duart3x** [comment]
So you only need to download this resource and ``` mythic_notify ```,

After that you need to:
- Import d3x_vehicleshop.sql in your database

- In your data base you will see your vehicles table where exists a new column ‘imglink’ (different from esx_vehicleshop) in that column you will put the image path like[imgs/mercerdes.png ] put the image in the HTM/imgs folder and add the file path to the fxmanifest.lua, if you want, you can use a img link like https://i.imgur.com/T6qCcNb.jpg that will work fine

- Add this in your server.cfg: ``` start d3x_vehicleshop ```
