### ISSUE TITLE
Test drive not working with latest fivem artifacts

### ISSUE THREAD

**Issue by kommatias** [Duart3x/d3x_vehicleshop#8]
Hi there, the test drive function is broken with latest fivem artifacts. To reproduce it just update your server to the latest artifact (windows/linux same behaviour) and try to test drive a vehicle. The ped spawns as it should at the airport, countdown timers and notifications are working as expected but the the vehicle model refuses to spawn. IT actually appears for a split-second and it disappears. Any ideas? Thank you in advance.

**Comment by bashon1** [comment]
some issue

**Comment by Sparah** [comment]
I have the same issue.

**Comment by kommatias** [comment]
Issue is unrelated to the resource.

**Comment by Davu9999** [comment]
Hello, 
Did you discover what is the issue?

Thank you very much
